Repository arangodb/oskar, pull requests merged in 2019-03, with the labels that each got.

#83 Properly handle 3.3- version parsing from CMakeLists.txt
  helper.psm1
Labels: PowerShell, Windows, bug

#85 Add all arango* binaries (Linux) and arango*.pdb files (Windows) if c…
  scripts/lib/Utils.psm1
  scripts/lib/tests.fish
Labels: Linux, Windows, enhancement, macOS

#86 Use buildStaticArangoDB in any regular oskar* execution
  helper.psm1
Labels: Windows

#87 Skip Drivers book in <= 3.3 / Compare book.json plugins only
  README.md
  containers/documentation.docker/buildLib
  containers/documentation.docker/build_documentation
Labels: bug

#90 Set parallelism to 24 for all Windows jobs
  jenkins/runCatchTest.ps1
  jenkins/runFullNightlyTest.ps1
  jenkins/runLimitedNightlyTest.ps1
  jenkins/runPRtest.ps1
Labels: bug

#91 Fix parallelism for Windows jobs to number of logical cores
  jenkins/runCatchTest.ps1
  jenkins/runFullNightlyTest.ps1
  jenkins/runLimitedNightlyTest.ps1
  jenkins/runPRtest.ps1
Labels: Windows, bug

#92 Doc - Do not delete output folders if keep_old=true
  containers/documentation.docker/build_documentation
Labels: bug

#94 Fix binaries and PDB archivation
  scripts/lib/Utils.psm1
  scripts/lib/tests.fish
Labels: Linux, PowerShell, Windows, bug, fish

#95 Add dump_multiple suite (for devel)
  scripts/runFullTests.fish
  scripts/runFullTests.ps1
  scripts/runLimitedTests.fish
  scripts/runLimitedTests.ps1
  scripts/runTests.fish
  scripts/runTests.ps1
Labels: Linux, Windows, enhancement, macOS
