Repository arangodb/oskar, pull requests merged in 2019-06, with the labels that each got.

#136 Feature/store configure cache
  helper.psm1
Labels: PowerShell, Windows, enhancement

#139 Set parallelism globally (Linux, macOS)
  helper.linux.fish
  helper.mac.fish
  jenkins/buildMaintainerMac.fish
  jenkins/runAsanNightlyTest.fish
  jenkins/runCatchTestMac.fish
  jenkins/runFullNightlyTest.fish
  jenkins/runFullNightlyTestMac.fish
  jenkins/runFullNightlyTestOnlyGrey.fish
  jenkins/runFullNightlyTestWithGrey.fish
  jenkins/runPRtestMac.fish
  jenkins/runQuickyTestMac.fish
Labels: Linux, macOS

#141 Double small parallelism for cluster tests
  scripts/lib/tests.fish
Labels: Linux, bug, macOS

#142 Should leave 10% of slots free when > 4
  scripts/lib/Utils.psm1
Labels: PowerShell, Windows
