Repository arangodb/oskar, pull requests merged in 2020-05, with the labels that each got.

#244 Use PsKill to stop timeouted tests
  helper.psm1
  scripts/lib/Utils.psm1
Labels: Jenkins, Windows

#245 Include hotfix version part into docker tag
  helper.fish
Labels: Docker

#177 Update runPRtest.ps1
  jenkins/runFullNightlyTest.ps1
  jenkins/runPRtest.ps1
Labels: Windows

#247 Feature/make dmg release tester fit
  dmg/3.4/ArangoDB3-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.4/ArangoDB3-CLI.app/Contents/Resources/arangod
  dmg/3.4/ArangoDB3-CLI.app/Contents/Resources/arangoimp
  dmg/3.4/ArangoDB3-CLI.app/Contents/Resources/arangosh
  dmg/3.4/ArangoDB3e-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.4/ArangoDB3e-CLI.app/Contents/Resources/arangod
  dmg/3.4/ArangoDB3e-CLI.app/Contents/Resources/arangoimp
  dmg/3.4/ArangoDB3e-CLI.app/Contents/Resources/arangosh
  dmg/3.5/ArangoDB3-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.5/ArangoDB3-CLI.app/Contents/Resources/arangod
  dmg/3.5/ArangoDB3-CLI.app/Contents/Resources/arangoimp
  dmg/3.5/ArangoDB3-CLI.app/Contents/Resources/arangosh
  dmg/3.5/ArangoDB3e-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.5/ArangoDB3e-CLI.app/Contents/Resources/arangod
  dmg/3.5/ArangoDB3e-CLI.app/Contents/Resources/arangoimp
  dmg/3.5/ArangoDB3e-CLI.app/Contents/Resources/arangosh
  dmg/3.6/ArangoDB3-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.6/ArangoDB3-CLI.app/Contents/Resources/arangod
  dmg/3.6/ArangoDB3-CLI.app/Contents/Resources/arangoimp
  dmg/3.6/ArangoDB3-CLI.app/Contents/Resources/arangosh
  dmg/3.6/ArangoDB3e-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.6/ArangoDB3e-CLI.app/Contents/Resources/arangod
  dmg/3.6/ArangoDB3e-CLI.app/Contents/Resources/arangoimp
  dmg/3.6/ArangoDB3e-CLI.app/Contents/Resources/arangosh
  dmg/3.7/ArangoDB3-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.7/ArangoDB3-CLI.app/Contents/Resources/arangod
  dmg/3.7/ArangoDB3-CLI.app/Contents/Resources/arangoimp
  dmg/3.7/ArangoDB3-CLI.app/Contents/Resources/arangosh
  dmg/3.7/ArangoDB3e-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/3.7/ArangoDB3e-CLI.app/Contents/Resources/arangod
  dmg/3.7/ArangoDB3e-CLI.app/Contents/Resources/arangoimp
  dmg/3.7/ArangoDB3e-CLI.app/Contents/Resources/arangosh
  dmg/default/ArangoDB3-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/default/ArangoDB3-CLI.app/Contents/Resources/arangod
  dmg/default/ArangoDB3-CLI.app/Contents/Resources/arangoimp
  dmg/default/ArangoDB3-CLI.app/Contents/Resources/arangosh
  dmg/default/ArangoDB3e-CLI.app/Contents/MacOS/ArangoDB3-CLI
  dmg/default/ArangoDB3e-CLI.app/Contents/Resources/arangod
  dmg/default/ArangoDB3e-CLI.app/Contents/Resources/arangoimp
  dmg/default/ArangoDB3e-CLI.app/Contents/Resources/arangosh
Labels: macOS

#249 Update OpenLDAP to 2.4.50 for 3.4+ versions
  containers/buildAlpine.docker/tools/install-openldap.sh
  containers/buildAlpine2.docker/tools/install-openldap.sh
  containers/buildAlpine3.docker/tools/install-openldap.sh
  containers/buildAlpine4.docker/tools/install-openldap.sh
  containers/buildUbuntu.docker/tools/install.sh
  containers/buildUbuntu2.docker/tools/install.sh
  containers/buildUbuntu3.docker/tools/install.sh
  containers/buildUbuntu4.docker/tools/install.sh
  helper.linux.fish
Labels: Dependencies, Linux
