Repository arangodb/oskar, pull requests merged in 2020-04, with the labels that each got.

#235 API check job with Go driver
  helper.linux.fish
  jenkins/forTestLocalDocker.fish
Labels: Jenkins

#209 run git with --progress, so ssh has some activity
  jenkins/helper/jenkins.fish
  scripts/buildExamples.fish
  scripts/checkoutArangoDB.fish
  scripts/checkoutEnterprise.fish
  scripts/checkoutMirror.fish
  scripts/checkoutUpgradeDataTests.fish
  scripts/createCompleteTar.fish
Labels: enhancement

#237 fix for fish3
  helper.mac.fish
  scripts/lib/build.fish
  scripts/lib/tests.fish
Labels: fish

#216 Feature/timings
  helper.fish
  scripts/lib/tests.fish
Labels: enhancement

#238 Bug fix/fix upgrade tests checkout
  helper.fish
  helper.psm1
  scripts/checkoutUpgradeDataTests.fish
Labels: bug

#239 OpenSSL 1.1.1f
  containers/buildAlpine.docker/Dockerfile
  containers/buildAlpine.docker/tools/install-openssl.sh
  containers/buildAlpine2.docker/Dockerfile
  containers/buildAlpine2.docker/tools/install-openssl.sh
  containers/buildAlpine3.docker/Dockerfile
  containers/buildAlpine3.docker/tools/install-openssl.sh
  helper.linux.fish
  scripts/buildMacOs.fish
Labels: enhancement

#241 Feature/gcc 9.3
  containers/buildAlpine4.docker/.gitignore
  containers/buildAlpine4.docker/Dockerfile
  containers/buildAlpine4.docker/tools/g++
  containers/buildAlpine4.docker/tools/gcc
  containers/buildAlpine4.docker/tools/install-openldap.sh
  containers/buildAlpine4.docker/tools/install-openssl.sh
  containers/buildAlpine4.docker/tools/install-poll.sh
  helper.linux.fish
  scripts/buildAlpine4.fish
Labels: Linux, enhancement

#242 Update containers with OpenSSL 1.1.1g
  containers/buildAlpine.docker/Dockerfile
  containers/buildAlpine2.docker/Dockerfile
  containers/buildAlpine3.docker/Dockerfile
  containers/buildAlpine4.docker/Dockerfile
  helper.linux.fish
Labels: enhancement

#243 Feature/activefailover docker
  jenkins/helper/adjust_port.inc
  jenkins/helper/port.sh
  jenkins/helper/server.inc
Labels: Docker, Drivers, Jenkins
