Repository arangodb/oskar, pull requests merged in 2020-09, with the labels that each got.

#264 Moved ENV variable to Dockerfile to enable it for k8s.
  containers/arangodb34.docker/Dockerfile
  containers/arangodb34.docker/entrypoint.sh
  containers/arangodb35.docker/Dockerfile
  containers/arangodb35.docker/entrypoint.sh
  containers/arangodb35ubi.docker/Dockerfile
  containers/arangodb35ubi.docker/entrypoint.sh
  containers/arangodb36.docker/Dockerfile
  containers/arangodb36.docker/entrypoint.sh
  containers/arangodb36ubi.docker/Dockerfile
  containers/arangodb36ubi.docker/entrypoint.sh
  containers/arangodb37.docker/Dockerfile
  containers/arangodb37.docker/entrypoint.sh
  containers/arangodb37ubi.docker/Dockerfile
  containers/arangodb37ubi.docker/entrypoint.sh
  containers/arangodbDevel.docker/Dockerfile
  containers/arangodbDevel.docker/entrypoint.sh
  containers/arangodbDevelubi.docker/Dockerfile
  containers/arangodbDevelubi.docker/entrypoint.sh
Labels: Docker, enhancement

#263 add "fuerte" test
  scripts/runFullTests.fish
  scripts/runFullTests.ps1
  scripts/runTests.fish
  scripts/runTests.ps1
Labels: enhancement

#266 Use main branch for docs
  helper.fish
Labels: Documentation
