Repository arangodb/oskar, pull requests merged in 2021-04, with the labels that each got.

#314 Immediately remove recursiveChown container on Linux
  helper.linux.fish
Labels: bug

#312 remove obsolete UNCONDITIONALLY_BUILD_LOG_MESSAGES variable
  helper.fish
  helper.linux.fish
Labels: bug

#300 How to re-generate errorfiles after changes to errors.dat
  README.md
Labels: Documentation

#316 Feature/mini chaos
  helper.fish
  helper.linux.fish
  jenkins/runMiniChaos.fish
  scripts/checkoutMiniChaos.fish
  scripts/startMiniChaos.fish
Labels: enhancement

#318 Rename ArangoDB VERSION file
  helper.fish
  scripts/switchBranches.fish
Labels: bug, macOS
