Repository arangodb/oskar, pull requests merged in 2021-12, with the labels that each got.

#362 Fix logrotate group (issue #13935) and copyright dates
  debian/3.6/community/control
  debian/3.6/community/copyright
  debian/3.6/enterprise/control
  debian/3.6/enterprise/copyright
  debian/3.7/community/control
  debian/3.7/community/copyright
  debian/3.7/enterprise/control
  debian/3.7/enterprise/copyright
  debian/3.8/community/control
  debian/3.8/community/copyright
  debian/3.8/enterprise/control
  debian/3.8/enterprise/copyright
  debian/3.9/community/control
  debian/3.9/community/copyright
  debian/3.9/enterprise/control
  debian/3.9/enterprise/copyright
  debian/default/community/control
  debian/default/community/copyright
  debian/default/enterprise/control
  debian/default/enterprise/copyright
  dmg/3.6/ArangoDB3-CLI.app/Contents/Info.plist
  dmg/3.6/ArangoDB3e-CLI.app/Contents/Info.plist
  dmg/3.7/ArangoDB3-CLI.app/Contents/Info.plist
  dmg/3.7/ArangoDB3e-CLI.app/Contents/Info.plist
  dmg/3.8/ArangoDB3-CLI.app/Contents/Info.plist
  dmg/3.8/ArangoDB3e-CLI.app/Contents/Info.plist
  dmg/3.9/ArangoDB3-CLI.app/Contents/Info.plist
  dmg/3.9/ArangoDB3e-CLI.app/Contents/Info.plist
  dmg/default/ArangoDB3-CLI.app/Contents/Info.plist
  dmg/default/ArangoDB3e-CLI.app/Contents/Info.plist
  rpm/3.6/arangodb3.logrotate
  rpm/3.6/arangodb3.spec.in
  rpm/3.6/arangodb3e.spec.in
  rpm/3.7/arangodb3.logrotate
  rpm/3.7/arangodb3.spec.in
  rpm/3.7/arangodb3e.spec.in
  rpm/3.8/arangodb3.logrotate
  rpm/3.8/arangodb3.spec.in
  rpm/3.8/arangodb3e.spec.in
  rpm/3.9/arangodb3.logrotate
  rpm/3.9/arangodb3.spec.in
  rpm/3.9/arangodb3e.spec.in
  rpm/default/arangodb3.logrotate
  rpm/default/arangodb3.spec.in
  rpm/default/arangodb3e.spec.in
Labels: bug

#360 [QA-185] build openssl from source for macos
  README.md
  helper.mac.fish
  scripts/buildMacOs.fish
  scripts/lib/build.fish
  scripts/tools/clang
  scripts/tools/clang++
  scripts/tools/sccache
  scripts/tools/sccache-apple-darwin-arm64
  scripts/tools/sccache-apple-darwin-x86_64
Labels: macOS, OpenSSL

#330 Enable ASan+UBSan+LSan and TSan
  containers/buildUbuntu3.docker/Dockerfile
  containers/buildUbuntu3.docker/tools/clang
  containers/buildUbuntu3.docker/tools/clang++
  containers/buildUbuntu4.docker/Dockerfile
  containers/buildUbuntu4.docker/tools/clang
  containers/buildUbuntu4.docker/tools/clang++
  containers/buildUbuntu5.docker/Dockerfile
  containers/buildUbuntu5.docker/tools/clang
  containers/buildUbuntu5.docker/tools/clang++
  helper.fish
  helper.linux.fish
  helper.mac.fish
  jenkins/buildExamples.fish
  jenkins/buildExamplesCoverage.fish
  jenkins/runAsanNightlyTest.fish
  jenkins/runCoverage.fish
  jenkins/runCoverageRocksDB.fish
  scripts/buildAlpine3.fish
  scripts/buildAlpine4.fish
  scripts/buildAlpine5.fish
  scripts/buildArangoDB3.fish
  scripts/buildArangoDB4.fish
  scripts/buildArangoDB5.fish
  scripts/buildMacOs.fish
  scripts/lib/tests.fish
  scripts/runFullTests.fish
  scripts/runOneTest.fish
  scripts/runTests.fish
  utils/build.sh
Labels: enhancement
