Repository arangodb/oskar, pull requests merged in 2022-11, with the labels that each got.

#450 Update OpenSSL to 1.1.1s
  containers/buildAlpine3.docker/Dockerfile
  containers/buildAlpine4.docker/Dockerfile
  containers/buildAlpine5.docker/Dockerfile
  containers/buildAlpine6.docker/Dockerfile
  containers/buildUbuntu3.docker/Dockerfile
  containers/buildUbuntu4.docker/Dockerfile
  containers/buildUbuntu5.docker/Dockerfile
  containers/buildUbuntu6.docker/Dockerfile
  helper.linux.fish
Labels: OpenSSL, cla-signed

#442 if coredump is to big, delete it instead of archiving
  jenkins/helper/test_launch_controller.py
Labels: cla-signed

#452 Fix usage of encryption at rest for testing.js
  helper.psm1
  jenkins/helper/test_launch_controller.py
  scripts/lib/Utils.psm1
Labels: cla-signed

#453 cleanup 'files', make sure 'files_unsorted' is an array
  jenkins/helper/test_launch_controller.py
Labels: cla-signed

#454 implement socket counting for mac
  jenkins/helper/test_launch_controller.py
Labels: cla-signed

#456 add mac filter, fix windows filter
  README.md
  jenkins/helper/test_launch_controller.py
Labels: cla-signed

#431 BTS-999: Small systems patches
  jenkins/helper/async_client.py
  jenkins/helper/test_launch_controller.py
Labels: cla-signed

#458 Switch all sanitizers builds to clang
  scripts/buildArangoDB3.fish
  scripts/buildArangoDB4.fish
  scripts/buildArangoDB5.fish
  scripts/buildArangoDB6.fish
Labels: cla-signed, Sanitizers

#459 don't use sudo inside the docker container we're running as root
  containers/buildUbuntu3.docker/Dockerfile
  containers/buildUbuntu4.docker/Dockerfile
  containers/buildUbuntu5.docker/Dockerfile
  containers/buildUbuntu6.docker/Dockerfile
  helper.linux.fish
  jenkins/helper/test_launch_controller.py
Labels: cla-signed

#460 split the huge file into its natural modules
  jenkins/helper/arangosh.py
  jenkins/helper/dmesg.py
  jenkins/helper/dump_handler.py
  jenkins/helper/launch_handler.py
  jenkins/helper/monkeypatch_psutil.py
  jenkins/helper/site_config.py
  jenkins/helper/socket_counter.py
  jenkins/helper/test_config.py
  jenkins/helper/test_launch_controller.py
  jenkins/helper/testing_runner.py
  jenkins/helper/tools/killall.py
Labels: cla-signed

#462 Feature/align tmp folder to testname
  jenkins/helper/arangosh.py
  jenkins/helper/async_client.py
  jenkins/helper/test_config.py
  jenkins/helper/testing_runner.py
Labels: cla-signed

#449 invoke machine cleaner
  jenkins/helper/prepareOskar.ps1
Labels: Windows, cla-signed

#461 Feature/clean docker containers
  helper.fish
  jenkins/helper/clear_machine.py
  jenkins/helper/jenkins.fish
Labels: cla-signed

#464 for the wintendo we need to use more force to get rid of stuck arango processes
  jenkins/helper/async_client.py
  jenkins/helper/testing_runner.py
  jenkins/helper/tools/killall.py
Labels: Windows, cla-signed

#465 QA-332: don't trip on files already existing
  jenkins/helper/site_config.py
  jenkins/helper/testing_runner.py
Labels: cla-signed

#468 the core pattern is like core-%p-%t, but we need globs.
  jenkins/helper/testing_runner.py
Labels: cla-signed

#469 use finally to marke sure the test properly deregisteres itself from the manager
  jenkins/helper/site_config.py
  jenkins/helper/testing_runner.py
Labels: cla-signed
