Repository arangodb/oskar, pull requests merged in 2022-05, with the labels that each got.

#388 Update OpenSSL to 1.1.1o and OpenLDAP to 2.6.2
  containers/buildAlpine3.docker/Dockerfile
  containers/buildAlpine3.docker/tools/install-openldap.sh
  containers/buildAlpine4.docker/Dockerfile
  containers/buildAlpine4.docker/tools/install-openldap.sh
  containers/buildAlpine5.docker/Dockerfile
  containers/buildAlpine5.docker/tools/install-openldap.sh
  containers/buildUbuntu3.docker/Dockerfile
  containers/buildUbuntu3.docker/tools/install.sh
  containers/buildUbuntu4.docker/Dockerfile
  containers/buildUbuntu4.docker/tools/install.sh
  containers/buildUbuntu5.docker/Dockerfile
  containers/buildUbuntu5.docker/tools/install.sh
  helper.linux.fish
Labels: enhancement, OpenSSL

#390 [TLA-7] Add CPPCheck for PR's
  helper.linux.fish
  jenkins/runCppcheckPR.fish
  scripts/cppcheck.sh
Labels: Jenkins, cppcheck

#389 Feature/rlog
  helper.fish
  helper.linux.fish
  helper.mac.fish
  helper.psm1
  jenkins/rlog/pr.fish
  jenkins/rlog/pr.ps1
  scripts/lib/Utils.psm1
  scripts/rlog/pr.fish
  scripts/rlog/pr.ps1
Labels: enhancement
