Repository arangodb/oskar, pull requests merged in 2022-08, with the labels that each got.

#407 Feature/openssl 1.1.1q openldap 2.6.3
  containers/buildAlpine3.docker/Dockerfile
  containers/buildAlpine3.docker/tools/install-openldap.sh
  containers/buildAlpine4.docker/Dockerfile
  containers/buildAlpine4.docker/tools/install-openldap.sh
  containers/buildAlpine5.docker/Dockerfile
  containers/buildAlpine5.docker/tools/install-openldap.sh
  containers/buildAlpine6.docker/Dockerfile
  containers/buildAlpine6.docker/tools/install-openldap.sh
  containers/buildUbuntu3.docker/Dockerfile
  containers/buildUbuntu3.docker/tools/install.sh
  containers/buildUbuntu4.docker/Dockerfile
  containers/buildUbuntu4.docker/tools/install.sh
  containers/buildUbuntu5.docker/Dockerfile
  containers/buildUbuntu5.docker/tools/install.sh
  containers/buildUbuntu6.docker/Dockerfile
  containers/buildUbuntu6.docker/tools/install.sh
  helper.linux.fish
Labels: enhancement, OpenSSL

#408 Try to fix sumbolyzer
  scripts/lib/tests.fish
Labels: Sanitizers

#395 Snippets: Explicitly mention the target architecture (x86-64)
  snippets/3.8/debian.html.in
  snippets/3.8/docker.community.html.in
  snippets/3.8/docker.enterprise.html.in
  snippets/3.8/k8s.community.html.in
  snippets/3.8/k8s.enterprise.html.in
  snippets/3.8/linux.html.in
  snippets/3.8/macosx.html.in
  snippets/3.8/rpm.html.in
  snippets/3.8/suse.html.in
  snippets/3.8/windows.html.in
  snippets/3.9/debian.html.in
  snippets/3.9/docker.community.html.in
  snippets/3.9/docker.enterprise.html.in
  snippets/3.9/k8s.community.html.in
  snippets/3.9/k8s.enterprise.html.in
  snippets/3.9/linux.html.in
  snippets/3.9/macosx.html.in
  snippets/3.9/rpm.html.in
  snippets/3.9/suse.html.in
  snippets/3.9/windows.html.in
Labels: Documentation

#413 added new cert hash
  helper.psm1
Labels: Windows

#415 Add multiarch repos for RPM and DEB
  scripts/createAll
  scripts/createRepo
Labels: enhancement, arm

#404 Fixed detection of wrong pull request
  github/updateGitHubStatus.js
Labels: Jenkins
